contact/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('contact/', views.Contact.as_view(), name='contact-urls'),
]

home/urls.py
from . import views
from django.urls import path

# Internal:
from .views import (home)


urlpatterns = [
   path('', home, name='home-urls'),
]

noalco4me/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home-urls'),
    path('recipes/', include('recipes.urls'), name='recipes-urls'),
    path('contact/', include('contact.urls'), name='contact-urls'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
]

recipes/urls.py
from . import views
from django.urls import path


urlpatterns = [
   path('', views.RecipesList.as_view(), name='recipes-urls'),
   path('add_recipes/', views.add_recipes, name='add_recipes'),
   path('edit_recipes/<slug:slug>', views.edit_recipes, name='edit_recipes'),
   path
   ('delete_recipes/<slug:slug>', views.delete_recipes, name='delete_recipes'),
   path('<slug:slug>/', views.RecipesDetail.as_view(), name='recipes-detail'),
   path('<slug:slug>', views.RecipesLike.as_view(), name='recipes_like'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    """Schema for the Contact model, to be used for a contact form"""
    fname = models.CharField(max_length=150)
    lname = models.CharField(max_length=150)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"New message from {self.fname} {self.lname}: {self.body}"

recipes/models.py
from django.db import models

from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify


STATUS = ((0, "Draft"), (1, "Published"))


class Recipes(models.Model):

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='recipes_like', blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Recipes, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def number_of_comments(self):
        return self.comments.count()

    def can_edit(self, request, slug):
        """Allows creator to edit recipes."""
        if self.author:
            return True
        else:
            return False

    def can_delete(self, request, slug):
        """Allows creator to delete recipes."""
        if self.author:
            return True
        else:
            return False


class Comment(models.Model):

    recipes = models.ForeignKey(
        Recipes, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField(default='')
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    """Contact form"""
    class Meta:
        """Meta class"""
        model = Contact
        fields = ('fname', 'lname', 'email', 'body',)

        labels = {
            'fname': 'First Name',
            'lname': 'Last Name',
            'email': 'Email',
            'body': 'Message',
        }

recipes/forms.py
from .models import Comment, Recipes
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class RecipesForm(forms.ModelForm):
    """Recipes form"""
    # Sets a required field on a Django model form.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].required = True

    class Meta:
        """meta class"""
        model = Recipes
        fields = (
            'title',
            'author',
            'content',
            'featured_image',
        )

        labels = {
            'title': 'Recipes Title',
            'author': 'Recipes Author',
            'content': 'Write your recipes here',
            'featured_image': 'cover image',
        }

contact/views.py
from django.shortcuts import render

from django.views import View
from django.contrib import messages
from .forms import ContactForm


class Contact(View):
    """ View to allow sending of messages """
    def get(self, request, *args, **kwargs):
        """Return data"""
        return render(
            request,
            'contact.html',
            {
                'contact_form': ContactForm()
            }
        )

    def post(self, request, *args, **kwargs):
        """Post data"""
        contact_form = ContactForm(data=request.POST)

        if contact_form.is_valid():
            contact_form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Thanks for your message! We will be in touch soon')

        else:
            contact_form = ContactForm()
        return render(
            request,
            'contact.html',
            {
                'contact_form': ContactForm()
            }
        )

recipes/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Recipes
from .forms import CommentForm, RecipesForm


class RecipesList(generic.ListView):
    model = Recipes
    queryset = Recipes.objects.filter(status=1).order_by('-created_on')
    template_name = 'recipes.html'
    paginate_by = 9


class RecipesDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Recipes.objects.filter(status=1)
        recipes = get_object_or_404(queryset, slug=slug)
        comments = recipes.comments.filter(approved=True).order_by
        ("-created_on")
        liked = False
        if recipes.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "recipes_detail.html",
            {
                "recipes": recipes,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Recipes.objects.filter(status=1)
        recipes = get_object_or_404(queryset, slug=slug)
        comments = recipes.comments.filter(approved=True).order_by
        ("-created_on")
        liked = False
        if recipes.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipes = recipes
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "recipes_detail.html",
            {
                "recipes": recipes,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


class RecipesLike(View):

    def post(self, request, slug):
        recipes = get_object_or_404(Recipes, slug=slug)

        if recipes.likes.filter(id=request.user.id).exists():
            recipes.likes.remove(request.user)
        else:
            recipes.likes.add(request.user)

        return HttpResponseRedirect(reverse('recipes-detail', args=[slug]))


@login_required()
def add_recipes(request):
    """renders add recipes form"""
    submitted = False
    if request.method == "POST":
        recipes_form = RecipesForm(request.POST, request.FILES)
        if recipes_form.is_valid():
            recipes_form.instance.creator = request.user
            recipes_form.save()
            messages.add_message
            (request, messages.SUCCESS, 'Your Recipes is awaiting approval.')
            return redirect('recipes-urls')
    else:
        recipes_form = RecipesForm
        if 'submitted' in request.GET:
            submitted = True
    return render(
        request,
        'add_recipes.html',
        {'recipes_form': recipes_form, 'submitted': submitted})


@login_required()
def edit_recipes(request, slug):
    """Recipes update/edit view"""
    recipes = get_object_or_404(Recipes, slug=slug)
    recipes_form = RecipesForm(request.POST or None, instance=recipes)
    context = {
        "recipes_form": recipes_form,
        "recipes": recipes
    }
    if request.method == "POST":
        recipes_form = RecipesForm(request.POST, request.FILES,
                                   instance=recipes)
        if recipes_form.is_valid():
            recipes = recipes_form.save(commit=False)
            recipes.creator = request.user
            recipes.save()
            messages.add_message(request, messages.SUCCESS, 'Recipe updated!')
            return redirect('recipes-urls')
    else:
        recipes_form = RecipesForm(instance=recipes)
    return render(request, "edit_recipes.html", context)


@login_required()
def delete_recipes(request, slug):
    """Delete recipes"""
    recipes = get_object_or_404(Recipes, slug=slug)
    recipes.delete()
    messages.add_message(request, messages.SUCCESS, 'Recipe deleted.')
    return redirect('recipes-urls')

templates/add_recipes.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    <title>Create your recipes here</title>
{% endblock %}

<!-- Add a recipe-form -->
{% block content %}
{% if user.is_authenticated %}
    <div class="container card-body">
        <h4 class="text-center">Create your recipes here</h4>
        <hr>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    {{ recipes_form | crispy }}
                </div>
                <br>
                <input type="submit" value="submit" class="btn btn-signup">
            </form>
   </div>

{% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="NonAlco4me app">
    <meta name="keywords" content="recipes, nonalco, drinks, soda">
    <meta name="author" content="Sinha">

    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Favicon here -->
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <!-- CSS -->
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
    <title>Non Alco 4me</title>
</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home-urls' %}">NonAlco4me</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarText">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home-urls' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes-urls' %}">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact-urls' %}">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Alert message goes here -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg text-center text-white">
            <div class="container p-2 pb-0">
                <div class="row">
                    <!-- Section: Address and Email -->
                    <section class="col-lg-4">
                        <h4>Our Address <i class="fa-regular fa-address-card"></i></h4>
                        <p>NonAlco4me<br>
                            Södra Esplanaden 26<br>
                            387 32 Borgholm
                            <br>Sweden
                        </p>
                        <h4>Our Email <i class="fa-regular fa-envelope"></i></h4>
                        <p>
                            Nonalco4me@mail.com
                        </p>
                        <br>       
                    </section>
                    <!-- Section: Social media -->
                    <section class="col mb-4">
                        <h4 class="my-4">Social Media</h4>
                        <a class="btn btn-outline-light btn-floating m-1" href="https://www.twitter.com" target="_blank"
                            role="button"><i class="fab fa-twitter"></i> Twitter</a>
        
                        <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/" target="_blank"
                            role="button"><i class="fab fa-linkedin-in"></i> LinkedIn</a>
        
                        <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/" target="_blank"
                            role="button"><i class="fab fa-instagram"></i> Instagram</a>
        
                        <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/" target="_blank"
                            role="button"><i class="fab fa-facebook"></i> Facebook</a>
                        <hr class="my-4">
                    </section>
                </div>       
            </div>
        
            <!-- Copyright -->
            <div class="text-center" id="copyright">
                © 2023 Copyright:
                <a class="text-white" href="{% url 'home-urls' %}">NonAlco4me | Educational Purpose Only</a>
            </div>
    </footer>

    <!-- Boostrap 5 JS so my navbar works in mobile devices -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>


    <!-- Font awesome added here-->
    <script src="https://kit.fontawesome.com/90f07a2b1c.js" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% load crispy_forms_tags %}


<section>
    <div class="container-fluid px-4 px-lg-5">
        <h2 class="mb-4 mt-3 text-center top-text">
            Contact Us
        </h2>
        <hr>
    </div>
</section>

<!-- Contact form -->
<div id="contact">
    <div class="container card-body">
        <div class="row">
            <div class="card col-12 col-md-6 contact-form">
                <div class="card-body">
                    <form method="post">
                        {{ contact_form | crispy }}
                        {% csrf_token %}
                         <br>
                        <button type="submit" class="btn main-btn btn-signup">Send</button>
                    </form>        
                </div>
            </div>
            <div id="map" class="col-12 col-md-6"></div>
        </div>
    </div>
</div>


<!-- Google maps -->
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-B1mZqSWhwklRPd0vr7ij6BD1Qb4NeUE&callback=initMap"></script>
    <script src="{% static 'js/maps.js' %}"></script>
    {% endblock %}

templates/delete_successful.html
{% extends "base.html" %}
{% load static%}
{% block content %}
<div class="container-fluid contact-form" id="contact-form">
    <h1>Your delete was successful!</h1>

</div>
{% endblock %}

templates/edit_recipes.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
<title>Edit Your Recipes Here</title>
{% endblock %}


{% block content %}
{% if user.id == recipes.author.id %}
<div class="card-body">
    <h4 class="text-center">Edit your recipes here</h4>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                {{ recipes_form | crispy }}
            </div>
            <br>
            <input type="submit" value="submit" class="btn btn-signup">
        </form>
</div>

{% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section>
    <div class="container-fluid px-4 px-lg-5">
        <h2 class="mb-4 mt-3 text-center top-text">
            Home
        </h2>
        <hr>
    </div>
</section>
<div id="hero-image" class="img-fluid">
    <div class="col-12">
        <div id="add-recipes" class="container-fluid hero-container">
            <div class="col-12">
                <div class="text-center text-white header-text">
                    <h1 class="text-center page-title">Welcome to NonAlco4me</h1>
               </div>
                <div id="add-recipes-text" class="p-3 text-center text-white header-text">
                     {% if user.is_authenticated %}
                     <p>
                        Here you can look for a non-alcoholic drink that strives for your needs. Or add a recipe yourself by pressing the button below.</p>
                     {% else %}
                     <p>
                        Here you can look for a non-alcoholic drink that strives for your needs. Or add a recipe yourself by <a class="sign-not-loggedin" href="{% url 'account_signup' %}">Signup</a> on the site or <a class="sign-not-loggedin" href="{% url 'account_login' %}">log in</a>.</p>
                     {% endif %}           
                     <div class="row text-on-top">
                         <!--Add a recipes-->
                         {% if user.is_authenticated %}
                         <div class="btn d-inline-block main-btn">
                             <a class="btn btn-lg" id="add-recipe-button" href="{% url 'add_recipes' %}" class="recipes-link">
                             Add recipes here +</a>
                         </div>
                         {% endif %} 
                     </div>
                 </div>    
            </div>    
         </div>
    </div>
</div>
<div id="about-text" class="container-fluid hero-container text-center">
    <hr>
    <h3 class="col-12">About us</h3>
    <hr>
    <p>
        Do you feel like you want to cool off with a good non-alcoholic drink but a regular soft drink is not something you prefer today. <br>
        Then you will find a drink that meets your needs on this page.
    <br>
    There are lots of different flavors and combinations. Maybe you fancy something fruity and sweet or why not a good lemon and tonic. <br>
    In addition to the drinks being delicious, they also look very good. <br> 
    Those who see your drink will definitely want one too. </p>
</div>

{% endblock content %}

templates/recipes.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section>
    <div class="container-fluid px-4 px-lg-5">
        <h2 class="mb-4 mt-3 text-center top-text">
            Recipes
        </h2>
        <hr>
    </div>
</section>

<div class="container-fluid">
    <div class="row">

        <!-- Recipes Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipes in recipes_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipes.featured_image.url %}
                                <img id="card-img" class="card-img-top"
                                    src="https://res.cloudinary.com/dbygidw1x/image/upload/v1691410422/static/images/pexels-taryn-elliott-4457151_copy1.a76955cb4e72.jpg" alt="a drink with lime and mint. Stands on a wooden tray">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipes.featured_image.url }}" alt="recipe picture of a drink that the user has chosen himself">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Creator: {{ recipes.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipes-detail' recipes.slug %}" class="recipes-link">
                                <h4 class="card-title">{{ recipes.title }}</h4>
                                <p class="card-text">{{ recipes.creator }}</p>
                            </a>
                            <hr>
                            <p class="card-text text-muted h6"><i class="far fa-heart"></i>
                                {{ recipes.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>

<!-- When it's more then 9 recipes on page a next button will appear -->
{% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock content %}

templates/recipes_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}
{% load static %}


<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">{{ recipes.title }}</h1>
                <p class="post-subtitle">{{ recipes.author }} | {{ recipes.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The placeholder image -->
                {% if "placeholder" in recipes.featured_image.url %}
                <img class="width-image" src="https://res.cloudinary.com/dbygidw1x/image/upload/v1691410422/static/images/pexels-taryn-elliott-4457151_copy1.a76955cb4e72.jpg" alt="a drink with lime and mint. Stands on a wooden tray">
                {% else %}
                <img class="width-image" src=" {{ recipes.featured_image.url }}" alt="recipe picture of a drink that the user has chosen himself">
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% if request.user.id == recipes.author.id %}
<!-- Edit Button, Delete Button and Delete Modal  -->
<div class="conatiner" id="modifyRecipes">
    <div class="row">
        <div class="col mt-2 mb-3 text-center">
            <!--Edit Button-->
            <a href="{% url 'edit_recipes' recipes.slug %}" class="edit"><button class="btn btn-outline-success btn-md"
                    value="{{ recipes.slug }}" type="button">Edit</button></a>
            <!--Delete Button-->
            <button class="btn btn-outline-danger btn-md mx4" data-bs-toggle="modal"
            data-bs-target="#deleteModal{{ recipes.id }}">Delete</button>
        </div>      
    </div>  
    <!--Delete modal-->
    <div class="modal fade" id="deleteModal{{ recipes.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content delete-modal">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"><i class="fas fa-times"></i></span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete "{{ recipes.title }}"?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger" href="{% url 'delete_recipes' recipes.slug %}">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <div class="card-text ">
                    {{ recipes.content | safe }}
                </div>
                <div class="row">
                    <div class="col-3">
                        {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'recipes_like' recipes.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="recipespost_id" value="{{recipes.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="recipes_id" value="{{recipes.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes -->
                        <strong class="text-secondary"> {{ recipes.number_of_likes }} </strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <!-- Comment section -->
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}